name: linting-wf
on:
 push:
  branches:
    - develop
 pull_request:
  branches:
    - develop
jobs:
 linting-job:
   runs-on: ubuntu-lates
   steps:
     - name: checkout repositry
       uses: actions/checkout@v4
     - name: install HTMLHint
       run: npm indstall --save-dev htmlhint
     - name: install Stylelint
       run: npm install --save-dev stylelint
     - name: Lint HTML Files
       run: npx htmlhint "**/*.html"
     - name: Lint CSS Files
       run: npx stylelint "**/*.css"
     - name: Display Package.json Contents
       run: cat package.json

     